"""Add sport column

Revision ID: 5e23409c1225
Revises: 
Create Date: 2026-03-01 21:42:03.710238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e23409c1225'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column already exists in a table."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = :table AND column_name = :col"
        ),
        {"table": table_name, "col": column_name}
    )
    return result.fetchone() is not None


def upgrade() -> None:
    if not _column_exists('accuracy_stats', 'sport'):
        op.add_column('accuracy_stats', sa.Column('sport', sa.String(), nullable=True))
    if not _column_exists('predictions', 'sport'):
        op.add_column('predictions', sa.Column('sport', sa.String(), nullable=True))
    # Create indexes (IF NOT EXISTS is implicit — Alembic skips if already present)
    try:
        op.create_index(op.f('ix_accuracy_stats_sport'), 'accuracy_stats', ['sport'], unique=False)
    except Exception:
        pass
    try:
        op.create_index(op.f('ix_predictions_sport'), 'predictions', ['sport'], unique=False)
    except Exception:
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_sport'), table_name='predictions')
    op.drop_column('predictions', 'sport')
    op.drop_index(op.f('ix_accuracy_stats_sport'), table_name='accuracy_stats')
    op.drop_column('accuracy_stats', 'sport')
    # ### end Alembic commands ###
